cards:
  message: "Welcome to EazyBank cards related Prod APIs"
  contactDetails:
    name: "John Cena- Developer"
    email: "johncena@eazybank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 555-4567
