loans:
  message: "Welcome to EazyBank loans related PROD APIs"
  contactDetails:
    name: "Kerian Cena- Developer"
    email: "keriancena@eazybank.com"
  onCallSupport:
    - (111) 555-1234
    - (111) 555-4567